name: Node.js CI - 2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        echo "NPM Install"
        npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.Azure_Login }}
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
    # Publish profile (*.publishsettings) file contents with Web Deploy secrets
       publish-profile: ${{ secrets.WebApp_Publisher_Profile }}
    # Name of the Azure Web App
       app-name: actiondeploy
    # Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
       package: package.json
    # Enter an existing Slot other than the Production slot
    #   slot-name: # optional, default is production
    
